TRADING_PAIRS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XAUUSD"]

TIMEFRAMES = ["15m", "1h", "4h", "1d"]

BINANCE_BASE_URL = "https://api.binance.com"

DATABASE_PATH = "data/crypto.db"

DEFAULT_CANDLE_LIMIT = 500

DEFAULT_TIMEFRAME = "1d"

SCHEDULER_INTERVAL_MINUTES = 15

GOLD_SYMBOL = "XAUUSD"